version: '1'
name: 'user-management-compose'

services:
  keycloak:
    container_name: 'keycloak'
    image: quay.io/keycloak/keycloak
    command: start-dev
    ports:
      - "9090:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    restart: unless-stopped
  db:
    container_name: 'user_management_db'
    image: postgres:16.2-alpine3.19
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=user_management
  user_management:
    build: .
    depends_on:
      - db
      - keycloak
    ports:
      - "8080:8080"
